### ISSUE TITLE
Add a commandline utility

### ISSUE THREAD

**Issue by mdboom** [spacetelescope/asdf#12]
For the basic operations -- implode/explode/garbage collect/validate.

**Comment by drdavella** [comment]
This currently exists for all but validate.

**Comment by drdavella** [comment]
@perrygreenfield and @nden, do we know what was intended by the `validate` command line tool? Files are automatically validated when they are opened. Is the point just to return whether or not a given file is well-formed ASDF or not?

**Comment by nden** [comment]
My guess, given the date of the issue, is that the code has evolved and this is not needed any more.

**Comment by drdavella** [comment]
Okay, that seems reasonable. It was also be very easy to provide a simple yes/no interface to indicate whether a file is valid or not. Although in the case that a file was not valid, you'd probably want to know why...

**Comment by drdavella** [comment]
Closing since a command line utility already exists. If a validation feature is specifically requested, we can open a new issue.
