### ISSUE TITLE
Scope of ASDF beyond Astronomy?

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/asdf#120]
At the moment, the tagline for the repo is _ASDF (Advanced Scientific Data Format) is a next generation interchange format for astronomical data_ - I wonder if it would be worth making it sound like it would also be useful to other fields, e.g. _being developed for astronomical and other scientific data_?

**Comment by astrofrog** [comment]
Note that it looks like the name is also being used for a new seismic data format:

http://asdf.readthedocs.org/en/latest/
https://pypi.python.org/pypi/pyasdf

:-/

**Comment by astrofrog** [comment]
Maybe for PyPI you should reserve https://pypi.python.org/pypi/asdf since it's still available?

**Comment by embray** [comment]
Oh, dammit.  When did that happen?  Maybe we need to rename again...

**Comment by embray** [comment]
If these seismology guys are serious about claiming the name ASDF for their data format we may need to rename; the potential for confusion is too great.  Unless we had prior art on it.  I'm not sure.

**Comment by mdboom** [comment]
That tagline is updated, and I've reserved `asdf` on PyPI (at least for now).  Bummer on this -- I could have sworn I did a PyPI search for "pyasdf" when we chose the name, and I should have squatted on the name then.  It's not the end of the world to rename this project/package to asdf from pyasdf, but that still doesn't resolve the potential confusion with the seismic folks.

**Comment by mdboom** [comment]
And of course, we have "pyasdf" on readthedocs and "asdf" on PyPI, and they have the inverse.  That's kind of a mess.  Maybe we could propose a friendly swap? ;(

**Comment by perrygreenfield** [comment]
Why didn't they call it amsdf?

**Comment by embray** [comment]
Yeah, even if we end up both using the name ASDF it looks like we'll have to talk.

**Comment by astrofrog** [comment]
Why not rename to USDF, the Ultimate Scientific Data Format? :wink:

**Comment by embray** [comment]
Or UIOP.  No ideas for what it stands for.  Maybe nothing.  Maybe everything.

**Comment by QuLogic** [comment]
\*cough* @krischer

**Comment by drdavella** [comment]
It looks like this issue has been addressed.
