### ISSUE TITLE
astropy dependency

### ISSUE THREAD

**Issue by rossant** [spacetelescope/asdf#151]
Can astropy be an optional dependency? Communities outside astronomy might be interested in using the file format.

**Comment by mdboom** [comment]
It's on our radar.  I just went ahead and created an explicit issue for this: #153.

**Comment by embray** [comment]
That's a good question.  Although I would argue that Astropy is not so onerous a dependency, I do think it should be possible to make the pyasdf implementation more generic eventually (for now a lot of the dependency on Astropy is out of convenience for development).

There are a couple areas where decoupling from Astropy is tricky though: Mainly the WCS support.  However, although WCS is one of the core data structures in the ASDF format, it is not needed for many files (although its use is broader than Astronomy) and so support for it is optional.

Time and units are two other important features used from Astropy.  A longer-term goal would be to support multiple time and unit libraries so long as they support the appropriate interfaces.

**Comment by drdavella** [comment]
Closing since this is addressed by #153.
