### ISSUE TITLE
Remove astropy as hard dependency

### ISSUE THREAD

**Issue by mdboom** [spacetelescope/asdf#153]

**Comment by mdboom** [comment]
Fixes #151.

**Comment by mdboom** [comment]
Just a status update: pyasdf itself no longer requires astropy, but running the tests does.  Once the testing framework in astropy has been sufficiently refactored out, we can remove the dependency there as well.

**Comment by drdavella** [comment]
Addressing issue #265 will be a big step towards this goal. We still need to separate the `astropy` testing framework from `astropy` proper, though.

**Comment by drdavella** [comment]
There's also an `astropy` dependency for parsing FITS files, although this may already be a 'soft' dependency.
