### ISSUE TITLE
Multiple ASDF extentions in single FITS file?

### ISSUE THREAD

**Issue by nden** [spacetelescope/asdf#176]
Afetr some limited playing with `fits_embed`, I see it can write only one ASDF extension with `extname=ASDF`. Is there a plan to allow more than one ASDF extension in a fits file with properly managed `extname` and `extver`?

**Comment by mdboom** [comment]
I had sort of assumed there would be a 1:1 relationship between FITS files and ASDF files.  Can you elaborate on why you would want more than one ADSF file in a FITS file?  As it stands now, you can still have multiple HDUs of data on the FITS side, all referred from a single ASDF tree in the ASDF extension.

**Comment by nden** [comment]
I was thinking about saving several WCS objects as separate ASDF extensions in the fits file and then referring to each from the appropriate FITS extension. But I see now this isn't supposed to work this way. When different WCSs are written in the same ASDF extension, does referencing the fits extensions (pairing a FITS data extension reference with a WCS) give some additional functionality on the FITS side? In other words should I always reference the fits extension on the ASDF side or does it not matter? Do I lose functionality if I make an ASDF tree which holds only WCSs?

**Comment by drdavella** [comment]
@nden just wondering if this is still relevant.

**Comment by drdavella** [comment]
Closing since this no longer appears to be a necessary use case. We can reopen if it becomes necessary in the future.
