### ISSUE TITLE
Diverged release version numbers on github and pypi

### ISSUE THREAD

**Issue by bsipocz** [spacetelescope/asdf#201]
It looks like that the package version numbering started to diverge between github and pypi with release 1.0.2 here is being the one uploaded as 1.1 to pypi (some discussion on it in #190).

Since then there are two release tags 1.0.3 and 1.0.4 that seem to be a continuation of the 1.1 version but not uploaded to pypi.

**Comment by nden** [comment]
It seems that after the `1.1` release on pypi the version was not updated in github.
Since the latest release on pypi (or anywhere else as far as I can tell) is `1.1` I suggest that the next release is tagged `1.1.1`. I will set this in `CHANGES.rst` unless there are objections.

**Comment by nden** [comment]
Fixed in the current release 1.2.0 and github.
