### ISSUE TITLE
asdf frames have diverged from the astropy implementation

### ISSUE THREAD

**Issue by nden** [spacetelescope/asdf#212]
More specifically astropy/astropy#5253 implemented `obsgeoloc` and `obsgeovel` as `CartesianRepresentation` objects (used to be `Quantity` objects).
The implementation in asdf needs to be fixed and the two relevant tests in test_wcs.py uncommented.

**Comment by drdavella** [comment]
This change is complete and a pull request will be submitted shortly. One complication is that `CartesianRepresentation` does not define equality, which means that our unit tests do not pass. There is an issue on astropy (https://github.com/astropy/astropy/issues/3182) but it doesn't appear that any work has been done yet.

**Comment by drdavella** [comment]
This was addressed in PR #244 and has been merged.
