### ISSUE TITLE
Capitalize "history" in history entries

### ISSUE THREAD

**Issue by bhilbert4** [spacetelescope/asdf#236]
Currently, in order for an asdf file to be a valid JWST reference file, the history keyword must be in all caps. Since the add_history_entry function uses lower case 'history', we cannot use this function when creating reference files. We can manually add a 'HISTORY' entry to the asdf tree, but this limits us to a single HISTORY entry, rather than allowing us to take advantage of the ability to have multiple 'history' entries. Would it be possible to change the 'history' entry to 'HISTORY'?

**Comment by nden** [comment]
I was playing with schemas for reference files and they are all failing because the keys are capitalized while the schemas are currently written to have their keys in lower case. I was going to suggest to make them all lower case keys. Is there a reason to have them in caps? FITS software will capitalize lower case keywords automatically so it's not a problem if you have a mixture of FITS and ASDF files.

**Comment by nden** [comment]
Just to clarify, I am talking about using lower case keys in ASDF files and in programming scripts. If the script writes out a FITS file, astropy.io.fits will capitalize the keywords.

**Comment by philhodge** [comment]
I like lower case keys.

**Comment by bhilbert4** [comment]
My motivation behind this was that the distortion reference file deliveries to CRDS are failing because the keyword is 'history' rather than 'HISTORY'. The failure comes about because CRDS looks specifically for upper case keywords. I asked the CRDS team in a roundabout way whether lower case 'history' would be ok but didn't get a response. I'll ask them again more directly. Currently I can work around the issue by manually setting model.tree['HISTORY'], but that limits me to a single HISTORY entry.

**Comment by nden** [comment]
Just talked to the ultimate expert on CRDS and he agrees asdf files should have lower case keywords. We need to take this up with the redcat team. And I mean *all* keywords should be lower case.
