### ISSUE TITLE
Cannot load json files under Python 3

### ISSUE THREAD

**Issue by bernie-simon** [spacetelescope/asdf#242]
Asdf uses generic_io to open schema files, which explicitly opens the files in binary mode. Under Python 3 reading a file opened in binary mode gives you a byte array. But the json parsing library expects to receive a string and throws an error message if it gets any other type:

TypeError: the JSON object must be str, not 'bytes'

**Comment by drdavella** [comment]
Do you have any code that reproduces this issue? I've been running the pytests in a Python 3 environment and haven't encountered this issue.

**Comment by drdavella** [comment]
Poking @bernie-simon to see if this is still a real issue or whether I can close it.
