### ISSUE TITLE
Missing __init__ file upon setup.py test

### ISSUE THREAD

**Issue by burke86** [spacetelescope/asdf#253]
After following instructions for installation here (installing all dependent libraries etc.) the test setup failed due to missing files:

![screenshot from 2017-06-19 21 55 49](https://user-images.githubusercontent.com/13906989/27313151-74c4af58-553a-11e7-835d-a63cf97f5243.png)

Thanks for the guidance!

P.S. I have tried on ubuntu and windows 10.

**Comment by nden** [comment]
@burke86 Do you have astropy installed? If so does this work:
```
from astropy.modeling import projections
```

**Comment by burke86** [comment]
re-installing astropy via pip did the trick.

Many thanks.
