### ISSUE TITLE
CompositeFrame schema disagrees with implementation

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#261]
The `CompositeFrame` JSON schema defines this object as either being an array of frames, or as being a single frame. However, the implementation of `CompositeFrame` only supports the array of frames. Which is correct? There are no tests for the latter case, and removing support for it would allow for simplified code since it would mean that the `CompositeFrame` schema version would not have to be bumped every time that the frame schema changes.

**Comment by drdavella** [comment]
Since the single frame case was not supported in code to begin with, I am strongly in favor of removing it altogether. However, I can't say I entirely understand all the use cases, so feedback is welcome.

**Comment by nden** [comment]
`GWCS` uses only an array of frames. I think it's OK to remove support for single frame.
