### ISSUE TITLE
Add usage examples of very big arrays to the documentation

### ISSUE THREAD

**Issue by yuvallanger** [spacetelescope/asdf#278]
I have tried using ASDF for saving big (for me) array data, but it always ended up with my RAM usage exploding.

Could you please demonstrate how one could save, load and change very big arrays in ASDF files?

**Comment by drdavella** [comment]
Hi @yuvallanger, just to be concrete and so I can try to reproduce your issues, can you give me a rough order of magnitude estimate of the size of your data? 10s of GB? 100s? Larger than that? Or smaller?

Also are you reading that data from another source on disk and copying it into an ASDF file or does that data start in memory before you try to save it?

**Comment by yuvallanger** [comment]
I am generating coordinates by analyzing video files. Each frame may contain ~100 points. Each video may be a few hours long at a 25 frame per second, so about:

(8 byte per float64) / (2 float64 per point) * (100 points per frame) * (25 frame per second) * (3 hours) = 412 MB.

That's quite small in comparison to the sizes you had in mind. I must be doing something extremely dumb.

Are there any example code in which arrays of my size (or yours) are involved?

**Comment by drdavella** [comment]
I definitely wouldn't assume that you're doing something dumb. I will dig around for some examples but in the meantime do you have a minimal code snippet to show what you're trying to do? I don't need the data itself but I'm just curious about your use case.

**Comment by yuvallanger** [comment]
Let's say I have a very long videos being analyzed, producing coordinates of the moving objects within each frame, so its columns will be `["frame_index", "x", "y"]`. If I were using CSV, I could save a coordinate per line in the file and not keep it all in memory before doing something like `ff.write_to(data_file)`

**Comment by drdavella** [comment]
Streaming data into an ASDF file is already supported, and there's already a [bit of documentation](http://asdf.readthedocs.io/en/latest/asdf/examples.html#streaming-array-data). I haven't looked at it much myself and the interface looks a little awkward, but maybe it can get you moving in the right direction. 

It looks like you could probably set your stream "row" width to be the size of a frame, or maybe a group of frames, and then just write out regularly instead of keeping it all in memory.

Does this make sense? I'll take a closer look at this functionality myself, but let me know if you have any questions or issues in the meantime.

**Comment by yuvallanger** [comment]
I managed to test the conversion from an already generated CSV file into an ASDF file. Managed to do it with with some pain in the data type definition and conversion part.

```
In [271]: with open('/home/yuval/test.asdf', 'wb') as fd:
     ...:     with open('2017-06-19.csv', 'r') as cfd:
     ...:         c = csv.reader(cfd)
     ...:         header = next(c)
     ...:         dtype = numpy.dtype(list(zip(header, ('int64', 'int64', 'int64', 'float64', 'float64'))))
     ...:         ff = asdf.AsdfFile(dict(data=asdf.Stream([1], dtype)))
     ...:         ff.write_to(fd)
     ...:         print(dtype)
     ...:         print(header)
     ...:         for row_index, row in enumerate(c):
     ...:             converted_row = tuple(numpy.int64(row[:3])) + tuple(numpy.float64(row[3:]))
     ...:             converted_row_array = numpy.array(converted_row, dtype=dtype)
     ...:             converted_row_str = converted_row_array.tostring()
     ...:             fd.write(converted_row_str)
     ...: new_ff = asdf.AsdfFile.open('/home/yuval/test.asdf'); new_ff.tree['data']
     ...: 
[('file_index', '<i8'), ('global_frame_index', '<i8'), ('local_frame_index', '<i8'), ('x', '<f8'), ('y', '<f8')]
['file_index', 'global_frame_index', 'local_frame_index', 'x', 'y']
Out[271]: 
array([[( 0,      5,    5,  1888.   ,   16.5   )],
       [( 0,      5,    5,  1845.49 ,   15.6997)],
       [( 0,      5,    5,  1803.   ,   14.5125)],
       ...,
       [(16, 823558, 9813,   558.741,  325.397 )],
       [(16, 823558, 9813,  1660.   ,  245.    )],
       [(16, 823558, 9813,   298.   ,  194.    )]],
      dtype=[('file_index', '<i8'), ('global_frame_index', '<i8'), ('local_frame_index', '<i8'), ('x', '<f8'), ('y', '<f8')])
In [273]: new_ff.tree['data'].shape
Out[273]: (7974018, 1)
```

**Comment by yuvallanger** [comment]
You can use this example code, if you'd like, in the documentation.

**Comment by drdavella** [comment]
Thanks! I adapted it and simplified it slightly as you'll see in the PR.
