### ISSUE TITLE
Get rid of 2to3

### ISSUE THREAD

**Issue by pllim** [spacetelescope/asdf#325]
As per https://github.com/astropy/astropy-helpers/issues/333#issuecomment-326035142 , `astropy-helpers` is dropping `2to3` support. If you don't get rid of it here, you cannot upgrade to use `astropy-helpers` for Astropy v3 or later.

**Comment by drdavella** [comment]
We need to come up with a real roadmap but I'm hoping to release a `1.3.0` version in the near future, and then maybe the next release would be `2.0.0` which would drop our own Py3 support entirely.

**Comment by pllim** [comment]
You don't need to drop Python 2 support for this. Just a bit more work to support both Python 2 and 3 if you are currently using `2to3` as shortcut.

p.s. Roadmap can go to https://github.com/spacetelescope/asdf/wiki if you don't mind it being public. Else, there's always, uh, Confluence.

**Comment by perrygreenfield** [comment]
There shouldn't be anyone using Python 2 with asdf (and I would be happy advertising the fact that we won't support Python 2 even now). No reason to complicate the development for something we don't intend to support.

**Comment by jdavies-st** [comment]
Isn't the JWST calibration pipeline being currently run under p27?  It depends strongly on `asdf`.

**Comment by perrygreenfield** [comment]
Let me check. The HST one has switched to 3 (as far as I understand). It would be odd for JWST to still be on 2, but you may be right.

**Comment by nden** [comment]
That should end with the September build. I believe we just delivered tcode to DMS packaged with python 3. astropy is also dropping support for python 2. Too bad we are still running reg tests under python 2.

**Comment by drdavella** [comment]
The main questions from my perspective (and the answers don't necessarily belong in this thread):

- do we have one more release of ASDF without dropping Py2 support (this would be 1.3.0 in October)?
- if so, do we provide some kind of deprecation warning for people that are still using Py2 in the 1.3.0 release?
- if not, and we drop Py2 support immediately, should we bump to v2.0.0?

**Comment by perrygreenfield** [comment]
Nadia is correct.

If another release isn't needed for the JWST delivery, I don't see why we need one for python 2.

Sure, we could bump it to V2. 

It may be good to contact anyone we know that is using it to see if dropping support for 2 is a problem (anyone who has raised an issue or sent an email?)
