### ISSUE TITLE
Deprecate and/or eliminate Python 2 support

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#326]
The main questions are the following:
- Should there be an intermediate 1.3.0 release that simply deprecates Python 2.7 support?
- Or should we immediately move to a 2.0.0 release that eliminates Python 2.7 support altogether?

This is related to #325 and closes #269.

**Comment by drdavella** [comment]
@vmarkovtsev, @yuvallanger, you are recent outside users/contributors that might be affected by this change. Do you have any objections to removing Python 2 support entirely in the next release?

**Comment by yuvallanger** [comment]
Go ahead. I use Python 3.

**Comment by vmarkovtsev** [comment]
I highly encourage dropping Python2, we use exclusively Python3.

**Comment by drdavella** [comment]
Thanks for the feedback. I think we will still end up doing a 1.3.0 release in the near term that deprecates Py2 support and then the following release will be a major version bump and will eliminate support entirely.
