### ISSUE TITLE
asdf installation issue?

### ISSUE THREAD

**Issue by nden** [spacetelescope/asdf#337]
I see errors when running GWCS tests on Travis related to python version requirements in asdf.
```
Collecting asdf from git+https://github.com/spacetelescope/asdf.git#egg=asdf
  Cloning https://github.com/spacetelescope/asdf.git to /tmp/pip-build-e737z6sl/asdf
asdf requires Python '~=2.7, >=3.3' but the running Python is 3.5.4
```

Full logs can be seen [here](https://travis-ci.org/nden/gwcs)

@drdavella Any suggestions?

**Comment by drdavella** [comment]
I think this is a bug in the way the version is is formatted. I just pushed a fix to master, so if you rerun the tests hopefully it will work this time...

**Comment by nden** [comment]
Yes, it's fixed now. Thanks.
