### ISSUE TITLE
semantic_version version requirement too strong

### ISSUE THREAD

**Issue by olebole** [spacetelescope/asdf#360]
The version of the "semantic_version" package is given as 2.6.0, which seems to be unnecessarily strong: There seems to be nothing in the [`ChangeLog`](https://github.com/rbarrois/python-semanticversion/blob/543299ebb0a73c9ee513ac1165ed3732aaa8c94f/ChangeLog) of semantic_version.
For the Debian build, we cannot just download newer versions of a package, and the semantic_version version in Debian is still 2.3.1. Building asdf with that version works however fine.

Could you consider reducing the version requirement for semantic_version?

**Comment by drdavella** [comment]
After a quick test run, it looks like 2.3.1 should be sufficient. I'll have to put together a new release, though. Just curious but what is the restriction in Debian that prevents you from downloading newer versions of the package?

**Comment by olebole** [comment]
Probably nothing; the maintainer just didn't update. I can ask him, but when it works with 2.3.1, I can immediately upload the new asdf version.

**Comment by drdavella** [comment]
Okay. I'm not sure how urgent this is so I'm not sure whether I should issue a 1.3.1 bugfix release today since I just released 1.3.0.

**Comment by olebole** [comment]
It is not urgent at all -- I already have a patch which I can apply in the meantime. It was just nice to have your confirmation.

**Comment by drdavella** [comment]
Thanks for the heads up. This was the first version of `asdf` to have this requirement, and I just assumed it was fine to go with the latest stable version. I wasn't aware that not all systems had access to it.
