### ISSUE TITLE
Exception due to shared inline data

### ISSUE THREAD

**Issue by bobpepin** [spacetelescope/asdf#368]
Hi,
the attached code raises the following exception:
```
File "/opt/miniconda/lib/python3.6/site-packages/asdf-1.3.1.dev980-py3.6.egg/asdf/block.py", line 649, in get_block
    raise TypeError("Unknown source '{0}'".format(source))
TypeError: Unknown source '[-1.0, 1.0]'
```

This is presumably due to the _block attribute being set to None when the inline array is first encountered during writing.
[inline_py.txt](https://github.com/spacetelescope/asdf/files/1421967/inline_py.txt)

**Comment by drdavella** [comment]
@bobpepin thanks for the bug report. I was able to reproduce and will try to get a fix out shortly.
