### ISSUE TITLE
Create ASDF extension registry interface

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#378]
Right now packages that provide custom schemas and/or implement ASDF tags need to pass an extension object to each call to `asdf.AsdfFile` or `asdf.open`. This is cumbersome and not at all ideal. We should provide a mechanism for registering extensions either on a per-process basis (e.g. a function that is called at the beginning of a program), or an a per-package basis (allowing extensions to be registered when a package is installed).

@Cadair suggested using entry points in `setup.py` to allow packages to register custom extensions. Packages would define their extensions something like this:
```python
# setup.py
from setuptools import setup

entry_points = {
    'asdf.extensions': ['foobar=foobar.extensions:FoobarExtension']
}

setup(entry_points=entry_points)
```

This seems like a really nice solution. It uses an existing mechanism provided by `setuptools`, and it avoids the more awkward solution of providing a top-level function like `asdf.register_extensions`.

**Comment by perrygreenfield** [comment]
Any downside to this approach?

**Comment by drdavella** [comment]
@perrygreenfield, a good question. One side effect is that if a package installs extensions in this way, those extensions will always be included by ASDF, even if they are not needed. For most cases this probably doesn't matter much, but maybe it's a good idea to provide both options.

**Comment by perrygreenfield** [comment]
That sounds like the best solution to allow both and see how it works.
