### ISSUE TITLE
Implement abstract base class for ASDF extensions

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#386]
Right now `AsdfExtension` implements `__subclasshook__` so that it can recognize foreign extensions even if the foreign extension doesn't inherit directly from `AsdfExtension`. In most cases, it is not appropriate for foreign extensions to inherit from `AsdfExtension`.

However, using an abstract base class that can be used as a parent for both `AsdfExtension` and other extensions would make this much cleaner. It would allow invalid extension definitions to be checked much earlier than they are right now.

cc @Cadair

**Comment by Cadair** [comment]
I will take a swing at this.

**Comment by drdavella** [comment]
Closing this issue. I opened it in the midst of a momentary lapse of reason. Ideally, I think that `AsdfExtension` should not implement `__subclasshook__` so that foreign extensions are required to inherit it explicitly, but it's probably not that important.
