### ISSUE TITLE
Automatically init submodule or give a more useful warning

### ISSUE THREAD

**Issue by eteq** [spacetelescope/asdf#396]
I just tried cloning a fresh asdf and when I tried to build I got: ``FileNotFoundError: [Errno 2] No such file or directory: 'asdf-standard/reference_files'``.  After a moment's thought I realized this was because I needed to `git submodule init` and `git submodule update`.

However, I suspect many potential users/contributors won't realize that, as submodules aren't that well-known of a thing.  I see it is in the README, but I wonder if it would also be good to catch this exeception and throw something like "you probably forgot to initialize the submodules.  Type git submodule update --init to do that"?

Alternatively, one could imagine just adding this to the submodules that the `setup.py` initializes along side the helpers. The challenge there is that the helpers machinery is a bit complicated for that, and I'm not sure offhand how to do that...

**Comment by drdavella** [comment]
What command did you run?
