### ISSUE TITLE
Add support for `set` types

### ISSUE THREAD

**Issue by mdboom** [spacetelescope/asdf#4]
This will need an extension to jsonschema, as well as an extension to the `tagged.py` module.

**Comment by justincely** [comment]
This looks like it can be accomplished with use of [uniqueness](https://spacetelescope.github.io/understanding-json-schema/reference/array.html#uniqueness) in the json schema.

Is there a known use-case for this functionality?

**Comment by drdavella** [comment]
This is already possible. No additional support is required.
