### ISSUE TITLE
example in docs for reading the data file

### ISSUE THREAD

**Issue by bblais** [spacetelescope/asdf#403]
Looking through the docs, especially the Get Started part, I notice no example of reading the data file and using the data.  Any good examples already somewhere?

**Comment by drdavella** [comment]
@bblais thanks for your interest in ASDF! I apologize for the sparse documentation: one of my goals over the next month or so is to substantially improve it and provide more examples.

In the meantime, here is an example of creating a fairly simple hierarchical data set, writing it out to a file, and reading it back in:
```python
>>> import asdf
>>> import numpy as np

>>> data = {'D1': np.linspace( 0, 100, 8*4,).reshape(8, 4), 
            'D2': np.linspace( 0, 100, 10*5, ).reshape(10, 5),
            'ND': {'D1': np.linspace( 0, 100, 10*5,).reshape(10, 5),
                   'D2': np.linspace( 0, 100, 8*4,).reshape(8, 4), }}

# Writing data to file on disk
>>> outfile = asdf.AsdfFile(data)
>>> outfile.write_to('data.asdf')

# Reading data from file on disk
>>> infile = asdf.open('data.asdf')
>>> infile.tree
{'D1': <array (unloaded) shape: [8, 4] dtype: float64>,
 'D2': <array (unloaded) shape: [10, 5] dtype: float64>,
 'ND': {'D1': <array (unloaded) shape: [10, 5] dtype: float64>,  'D2': <array (unloaded) shape: [8, 4] dtype: float64>}}
# Data arrays can be accessed hierarchically from the top-level tree:
>>> infile.tree['D1']
array([[   0.        ,    3.22580645,    6.4516129 ,    9.67741935],
       [  12.90322581,   16.12903226,   19.35483871,   22.58064516],
       [  25.80645161,   29.03225806,   32.25806452,   35.48387097],
       [  38.70967742,   41.93548387,   45.16129032,   48.38709677],
       [  51.61290323,   54.83870968,   58.06451613,   61.29032258],
       [  64.51612903,   67.74193548,   70.96774194,   74.19354839],
       [  77.41935484,   80.64516129,   83.87096774,   87.09677419],
       [  90.32258065,   93.5483871 ,   96.77419355,  100.        ]])
>>> infile.tree['ND']
{'D1': <array (unloaded) shape: [10, 5] dtype: float64>,
 'D2': <array (unloaded) shape: [8, 4] dtype: float64>}
```

Please let me know if you have any other questions or would like any more specific examples.

**Comment by bblais** [comment]
Thanks!

The one example that I would like to know right now is how to load all of the tree at once, rather than just as referenced.  If I have:

>>> data={'X':[np.random.rand(40,40) for _ in range(10)]}

to be able to load the whole thing, so that my loaded data structure is the same as the saved one.

**Comment by drdavella** [comment]
@bblais I'm actually not aware of a way to force-load all arrays in the tree. The contents of arrays are lazy-loaded when they are accessed. However, I'm interested in your use case since I'm not sure if we have considered scenarios where lazy-loading is not acceptable. Can you provide more context? We can consider adding this as a feature in future versions if it seems useful.

**Comment by bblais** [comment]
I'll have to play with this for a while to see - my first use-case turned out to not really matter, I just had to think in a different way.  If I come up with a better one I'll let you know!  Thanks!

**Comment by drdavella** [comment]
Closing since this should now be reflected in the README.
