### ISSUE TITLE
fits_embed inlines binary tables

### ISSUE THREAD

**Issue by bernie-simon** [spacetelescope/asdf#404]
Datamodels calls the code in fits_embed.py to serialize the asdf tree it creates so that it can be written to the asdf extension. Binary tables in the asdf tree are inlined in the serialization. This results in saved fits files having two copies of the binary table. A patch has been added to datamodels as a temporary fix, but the issue should be resolved in the asdf code.

**Comment by drdavella** [comment]
The related issue in JWST is https://github.com/STScI-JWST/jwst/issues/1565.
