### ISSUE TITLE
Developer usability concerns

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#414]
There are a few issues that bite new developers (and, speaking from experience, even some more experienced ones) when trying to get started with ASDF and building from source:
* making sure the `asdf-standard` submodule is initialized and up-to-date
* the fact that it is not possible to import and use `asdf` from the source directory

It would be nice to address these issues somehow so that new developers are not put off by the project.

**Comment by Cadair** [comment]
What get's me is the fact that doing `pip install -e .` doesn't work, i.e. even trival changes to the python source are not reflected in the imported version. This is probably the same as being able to import it from the source directory.

**Comment by drdavella** [comment]
@Cadair this should be fixed on the latest master. The problem appears to have been the use of `use_2to3` in `setup.py`, which was removed in #409.

**Comment by drdavella** [comment]
Closing since the major issues here have been addressed. A solution for making sure `asdf-standard` is always up to date exists in #419, but I am hesitant to merge this due to potential security issues.
