### ISSUE TITLE
Provide API for allowing other packages to validate schemas and examples

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#423]
Now that other packages are providing their own ASDF schemas (e.g. `astropy` and `gwcs`), it would be useful if they had the ability to test those schemas in the same way that ASDF currently tests its own schemas. This should include making sure that the schemas themselves are valid, as well as testing any examples provided in the schemas.

**Comment by nden** [comment]
Could you give some pointers where in asdf is the testing appening.

**Comment by drdavella** [comment]
The function `test_schema_example` in `asdf/tests/test_asdf_schemas.py` tests a single example. The schemas and examples are iterated over by the `pytest_generate_tests` hook in the same file.

**Comment by nden** [comment]
Thanks!
