### ISSUE TITLE
WCS reference in top-level ASDF schema is out of date

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#426]
This is related to #417.

**Comment by drdavella** [comment]
@nden, @perrygreenfield I think I'd like to propose removing the top-level `data`, `fits`, and `wcs` fields from newer versions of the ASDF core schema. Here's a few reasons why:
* They over-specify the core schema and make it inflexible and difficult to maintain.
* Their presence leads to unexpected warnings and errors when users try to use those fields (quite sensibly) for other purposes. For example, maybe I want my top-level `data` object to be a dictionary: the current schema won't allow it. 
* It doesn't look like JWST data products use any of these fields anyway. 

I need to think it through a bit more, though.

cc @Cadair

**Comment by Cadair** [comment]
This has caught me out many a time.

**Comment by drdavella** [comment]
@nden, @perrygreenfield, now that WCS schemas have moved out of ASDF and into GWCS, I think we should remove the `wcs` field from the top-level core schema. Otherwise, a top-level attribute of the ASDF core schema will be tied to a type that exists in a separate package. 

Users will still be free to use a top-level `wcs` field in the tree, but it will not need to be any particular kind of object. As far as I can tell, the JWST data products do not use the top-level `wcs` field at all.

I understand the original intent behind `data` and `wcs`, and it makes sense, but I'm not sure it justifies the cost of reduced flexibility. However, I'm willing to leave `data` as-is, and possibly to implement a better warning/error for when it is used incorrectly.
