### ISSUE TITLE
YAML formatting issues

### ISSUE THREAD

**Issue by mdboom** [spacetelescope/asdf#43]
This is a placeholder to remind to deal with some issues with how the YAML is output.

Since YAML has multiple ways to represent the same thing, there are cases where it might be preferable to use one form over another.  Currently, pyasdf does "whatever PyYAML does by default".

There are (at least) three separate things to consider here:
- When reading an input file, preserving the form of each of the input entries when writing back out
- When generating a file from scratch, using hints in the schema to select an output form
- Allowing the user to explicitly specify the form of the output on an individual item basis

**Comment by drdavella** [comment]
This already seems to have been addressed, so closing.
