### ISSUE TITLE
Intermittent failure loading external schemas/tags

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#430]
This is a fun one. It's almost certainly due to expectations of dictionary ordering somewhere in the guts of the type index machinery since it only seems to be reproducible on Python 3.5.

The failures look something like the following:
https://travis-ci.org/astropy/astropy/jobs/332871390#L5044

This affects the movement of tags to Astropy and GWCS.

cc @Cadair

**Comment by drdavella** [comment]
@Cadair thanks for the update and additional data. I assume this was observed on 3.5 and not 3.6?

**Comment by drdavella** [comment]
I added a gist for a small reproducer for the bug [here](https://gist.github.com/drdavella/18aae94198383e6ef4846c5dc7d1390f).

**Comment by Cadair** [comment]
Yeah on 3.5 again.

On 25 January 2018 21:48:22 GMT+00:00, drdavella <notifications@github.com> wrote:
>@Cadair thanks for the update and additional data. I assume this was
>observed on 3.5 and not 3.6?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/spacetelescope/asdf/issues/430#issuecomment-360611605

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
