### ISSUE TITLE
FITS hdu.info() no longer reports size information about ASDF extension

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/asdf#451]
Previously when the ASDF metadata was stored in an `IMAGE` extension, running `fits.info()` would provide information about the size of the extension.

Now that we are using a non-standard FITS extension to store ASDF data, it seems like this information is not available. Presumably this is because Astropy's `io.fits` does not know how to interpret the extension, so it doesn't know how to extract length information.

It would be useful if there was some way to allow Astropy to determine the length of extension.

cc @hbushouse

**Comment by philhodge** [comment]
It looks to me as if you can still use the BITPIX and NAXIS1 keywords to get the length of the data block.  I just ran a test with a file that had:

XTENSION= 'ASDF    '           / ASDF extension

NAXIS1 was 5760, with BITPIX = 8.  There were only 9 header keywords, so the header took one block, and 5760 is exactly two blocks, so the total size of the ASDF extension should be 3 * 2880 bytes.  I added up the sizes of the other HDUs (a primary HDU and one IMAGE extension) and added 3 * 2880 to that, and the total did agree with the actual file size of 50365440 bytes.

**Comment by drdavella** [comment]
@philhodge thanks, that is useful information. I think the main issue comes down to whether we can convince `astropy.io.fits` to report this length information in a useful way (for example when using `.info()`. I'm a bit pessimistic since from Astropy's perspective the `ASDF` extension is non-standard, and so it doesn't know how to interpret the various keywords. My guess is that the only solution would be to ask Astropy to explicitly support the ASDF extension.

**Comment by philhodge** [comment]
That's why I did the arithmetic, to check that the NAXIS1 keyword was correct, i.e. that the sum of the numbers of bytes agreed with `ls -l`.  The BITPIX and NAXIS* keywords have to be populated correctly so that a FITS reader can skip over an extension without having to read and interpret its contents.  I realize that the ASDF extension is the last one, but nothing prevents me from appending another extension of a different type.  `astropy.io.fits` must get the size of each extension by checking the number of header keywords and the values of the BITPIX and NAXIS* keywords, regardless of the type of the extension.  Why it doesn't do so for 'ASDF' I don't know, but there's no reason that it couldn't, even without supporting that extension type in any way other than assuming it follows the FITS standard for required keywords.

**Comment by drdavella** [comment]
Okay, I'll look into this on the Astropy side then, to see if something can be done. It should be possible for Astropy to report the values of the `NAXIS*` keywords even for non-standard extensions, so maybe it's just a matter of making a small change to `astropy.io.fits`.

@hbushouse, it looks like at the very least we might be able to report the value of `NAXIS1` for ASDF extensions. I need to look into the reasons for this a little more, but right now I believe this is always a multiple of 2880, so it won't necessarily reflect the actual size of the ASDF metadata contents.

**Comment by perrygreenfield** [comment]
I don't believe NAXIS1 must reflect the actual size of the data component in FITS. It should reflect the actual size of the ASDF content. FITS is just required to pad it to multiples of 2880.

**Comment by drdavella** [comment]
@perrygreenfield, thanks. I think this means I need to adjust the ASDF HDU code as well.

**Comment by philhodge** [comment]
The NAXISi keywords give the number of pixels along each, so you need to multiply it (or them, if NAXIS > 1) by abs(BITPIX) / 8 to get bytes.

**Comment by hbushouse** [comment]
Previously, when XTENSION='IMAGE' for ASDF extensions, astropy.io.fits.info() would report the "size" just by printing the value of NAXIS1 (as is done for other extensions that are true images - it reports naxis1 x naxis2 x ... x naxisn). So we don't really need to convert to bytes (IMHO).

**Comment by perrygreenfield** [comment]
Presumably ASDF extensions have a BITPIX of 8, right?

**Comment by drdavella** [comment]
@perrygreenfield yes, it's 8.

**Comment by drdavella** [comment]
So this boils down to two separate fixes: on the ASDF side, we don't need to pad the `NAXIS1` value out to a full card length; and on the Astropy side, it should be possible for `io.fits` to report `NAXIS*` values even for non-standard extensions.

**Comment by perrygreenfield** [comment]
That seems like the reasonable thing to do.

**Comment by drdavella** [comment]
@hbushouse this should be addressed by the combination of https://github.com/astropy/astropy/pull/7206 and #452.

**Comment by drdavella** [comment]
@hbushouse, @perrygreenfield, @philhodge this should be available now with the latest development versions of `asdf` and `astropy`.

If you open an older version of a file with `XTENSION=ASDF` (i.e. one that was created in the past month or two), you'll notice the reported length is padded to 2880 bytes. However, this should be corrected for all files with `XTENSION=ASDF` that are created from this point forward.
