### ISSUE TITLE
ValueError: Invalid value for all_array_storage: 'zlib'

### ISSUE THREAD

**Issue by OxygenLiu** [spacetelescope/asdf#466]
+ pipenv virtualenv 
+ Python 3.6 
+ asdf 1.3.2 

`af.write_to('compressed.asdf', all_array_storage='zlib')` generates  error message `ValueError: Invalid value for all_array_storage: 'zlib'` .

Is there any special setup for a virtualenv to access zlib?

**Comment by drdavella** [comment]
Hi @OxygenLiu, it looks like you're trying to compress the binary data blocks on output. In this case,
the parameter you need to use is actually `all_array_compression`, not `all_array_storage`. This should work just fine with `'zlib'` out of the box. Please let me know if you still have issues.

**Comment by drdavella** [comment]
Whoops, sorry about that!
