### ISSUE TITLE
When raising OSError, AsdfFile.update should highlight why associated file is read-only

### ISSUE THREAD

**Issue by Legendin** [spacetelescope/asdf#469]
Hello, new user here. First off I would like to thank you for your work on ASDF, it fits the bill perfectly for a pipeline project I'm working on and it's been a joy to use so far. I'm really looking forward to 2.0 and custom schemas. As I get more familiar with the package I would like to get involved by e.g. helping out with documentation.

Speaking of, I found the following behaviour somewhat confusing at first:
```
In [1]: import asdf
In [2]: f = asdf.open("test.asdf")
In [3]: f.update()
```
Results in:
```
OSError: Can not update, since associated file is read-only
```
From the exception or the docstring of `AsdfFile.update` it is not obvious that the cause is that the mode defaults to read-only in `AsdfFile.open`. While I don't disagree with the default behaviour, I wonder if it would be clearer to users if the exception was amended to indicate the likely cause. Or perhaps adding a line to the docstring reminding users that `AsdfFile.update` won't work unless the `mode` parameter of `AsdfFile.open` is set to "rw".

**Comment by drdavella** [comment]
@Legendin thanks for your feedback! It's great to hear that your experience with ASDF has been so positive. 

Contributions of all kinds are welcome. I am (slowly) working on improving the documentation and I am happy to consider any suggestions or contributions you'd like to provide.

I agree that the error message in this case could be more useful. If you are interested in making the change yourself, I would be happy to review any improvements to the error message and/or docstring.

**Comment by Legendin** [comment]
@drdavella I'm glad to hear that you're open to outside contributions. Your suggestion is exactly what I was hoping for; I'll send a PR your way soon :)
