### ISSUE TITLE
[2.0.0] AttributeErrors during build time tests

### ISSUE THREAD

**Issue by olebole** [spacetelescope/asdf#499]
Additionally to #498, there are a number of `AttributeError`s:

```________________________ test_missing_extension_warning ________________________

    def test_missing_extension_warning():
    
        yaml = """
    history:
      extensions:
        - !core/extension_metadata-1.0.0
          extension_class: foo.bar.FooBar
          software: !core/software-1.0.0
            name: foo
            version: 1.2.3
        """
    
        buff = yaml_to_asdf(yaml)
        with pytest.warns(None) as warnings:
>           with asdf.open(buff) as af:

asdf/tags/core/tests/test_history.py:136: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
asdf/asdf.py:766: in open
    ignore_missing_extensions=ignore_missing_extensions)
asdf/asdf.py:678: in _open_impl
    ignore_missing_extensions=ignore_missing_extensions)
asdf/asdf.py:638: in _open_asdf
    self._check_extensions(tree, strict=strict_extension_check)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <asdf.asdf.AsdfFile object at 0x7f3748917358>
tree = {'history': {'extensions': [{'extension_class': 'foo.bar.FooBar', 'software': {'name': 'foo', 'version': '1.2.3'}}]}}
strict = False

    def _check_extensions(self, tree, strict=False):
        if 'history' not in tree or not isinstance(tree['history'], dict) or \
                'extensions' not in tree['history']:
            return
    
        for extension in tree['history']['extensions']:
            filename = "'{}' ".format(self._fname) if self._fname else ''
>           if extension.extension_class not in self._extension_metadata:
E           AttributeError: 'TaggedDict' object has no attribute 'extension_class'

asdf/asdf.py:151: AttributeError
```

Another one:

```
_____________________________ test_mask_arbitrary ______________________________

    def test_mask_arbitrary():
        content = """
        arr: !core/ndarray-1.0.0
          data: [[1, 2, 3, 1234], [5, 6, 7, 8]]
          mask: 1234
        """
    
        buff = helpers.yaml_to_asdf(content)
        with asdf.AsdfFile.open(buff) as ff:
            assert_array_equal(
>               ff.tree['arr'].mask,
                [[False, False, False, True], [False, False, False, False]])
E           AttributeError: 'TaggedDict' object has no attribute 'mask'

asdf/tags/core/tests/test_ndarray.py:334: AttributeError
```

and:

```
______________________________ test_inline_string ______________________________

    def test_inline_string():
        content = "arr: !core/ndarray-1.0.0 ['a', 'b', 'c']"
        buff = helpers.yaml_to_asdf(content)
    
        with asdf.AsdfFile.open(buff) as ff:
>           assert_array_equal(ff.tree['arr']._make_array(), ['a', 'b', 'c'])
E           AttributeError: 'TaggedList' object has no attribute '_make_array'

asdf/tags/core/tests/test_ndarray.py:374: AttributeError
```

and:

```
______________________________ test_undefined_tag ______________________________

    def test_undefined_tag():
[...]
        buff = helpers.yaml_to_asdf(yaml)
        with pytest.warns(None) as warning:
            afile = asdf.AsdfFile.open(buff)
            missing = afile.tree['undefined_data']
    
        assert missing[0] == 5
        assert missing[1] == {'message': 'there is no tag'}
>       assert (missing[2] == array([[1, 2, 3], [4, 5, 6]])).all()
E       AttributeError: 'bool' object has no attribute 'all'

asdf/tests/test_asdftypes.py:333: AttributeError
```

**Comment by olebole** [comment]
The full build log (with many more failures and errors) is attached.
[python-asdf_2.0.0-1_amd64.build.txt](https://github.com/spacetelescope/asdf/files/1934578/python-asdf_2.0.0-1_amd64.build.txt)

**Comment by drdavella** [comment]
I need to take a closer look, but these errors suggest to me that the package is not actually installed in the environment before the tests begin. Could this be the case? I'm not sure how your build/test script works, so if you can provide any details that would be useful.

**Comment by drdavella** [comment]
I was able to replicate these failures by building the package, installing its dependencies, and then running `pytest` from within the build package, without actually installing the package itself. Please install the package before testing.

**Comment by drdavella** [comment]
The way that new way ASDF registers extensions is by installing `setuptools` entry points. Without these entry points installed, ASDF does not know how to serialize/deserialize specific types, which leads to the errors in the test suite. This is a new feature in v2.0 and greatly improves the way that packages like Astropy provide ASDF extensions.

The package does not need to be installed to the final location: can you install the package in a virtual environment as part of the build procedure and test it there? Are there really no other Python packages that need to be installed before testing? It is my understanding that running tests against installed code is considered best practice.

If not, it may be possible for me to implement a workaround for Debian builds, but I probably won't be able to get around to it for another few weeks.

**Comment by olebole** [comment]
All packages that are needed for test are installed in a throw-away chroot before the (automatic) build starts, so there is no need for an extra virtual environment.
I thought that `entry_point` is to define shell scripts, but the tests don't involve shell scripts?
Can't I install the entry-points in-place in the build dir?
We do two types of tests: one is just after the build (before the package is finally created), to ensure that the build results in a working package. This is done during the build process, for each architecture (and also f.e. when the package is backported). And the other is done with the installed package, every time one of the dependencies changed. The latter is used to detect incompatible changes in the environment. But this is only done for our main architecture (x86_64) and for the current testing distribution (Buster). So, we try to somehow follow both ways.

**Comment by drdavella** [comment]
One of the uses of entry points is indeed to install command line scripts, but it is also commonly used to register plugins, which is how ASDF is using them. As far as I know, there's no way to actually register the entry points without running either `setup.py install` or `setup.py develop` in your environment.

Is your script able to set an environment variable? For example, if I added a workaround and required you to set a variable like `ASDF_NO_EXTENSIONS`, would that work for you? The problem is that you still won't be testing the package the way it will actually be seen by users.

**Comment by olebole** [comment]
That would really help me, thanks for the efforts! My major goal to have this is to detect platform dependent problems at build time, f.e. like in #235.
