### ISSUE TITLE
Abstract history reader interface

### ISSUE THREAD

**Issue by jaytmiller** [spacetelescope/asdf#500]
On read-the-docs there's a clear example of how to add/write ASDF history.   I could not see how to read one back.  Is there any kind of API for reading history,  say into an ordered list of tuples similar to:

[ (date, ... description ...),
  ...
]

Having an abstract API could insulate callers from changes in the underlying tree format.   Does an API exist?

**Comment by drdavella** [comment]
There is not currently an API for reading the history, but I will mark this as a feature request for `v2.1`.
