### ISSUE TITLE
Creating asdf files from C/C++

### ISSUE THREAD

**Issue by manodeep** [spacetelescope/asdf#504]
Thanks for creating the file format and the associated software - looks great!

I am interested in creating `asdf` files from C/C++. I looked through the docs but I couldn't figure out how to do so without implementing the entire functionality in C/C++. Is there any existing functionality that allows me to create `asdf` files directly from C/C++?

My apologies if I have missed something in the docs. And thanks again!

**Comment by drdavella** [comment]
Hi @manodeep thanks for your interest in ASDF!

There is not currently a fully functioning implementation of ASDF for C/C++. Coincidentally, right at this moment I am working on a prototype implementation over at https://github.com/spacetelescope/asdf-cpp, but I can't tell you for sure when it will be ready for use. I hope to have very basic functionality available in the next few weeks, but I can't make any guarantees.

In the meantime, if you don't care about performance, you could consider calling the Python code from your C/C++ code, but it would be a bit of a hack: https://docs.python.org/3.6/extending/embedding.html

**Comment by manodeep** [comment]
Thanks for the quick response! 

And going the wrong way (C->Python) is what I was thinking as well :) I suppose if you put the python in a separate thread and let the file writing occur independently, then there is no performance penalty...

Good luck with the C++ implementation. Please let me know (via a github mention is fine) when that implementation is done. Thanks again!

(Please feel free to close this issue)

**Comment by drdavella** [comment]
Closing this issue. Please see https://github.com/spacetelescope/asdf-cpp for a prototype implementation of ASDF in C++.
