### ISSUE TITLE
external storage "Resolved to relative URL" error

### ISSUE THREAD

**Issue by isonder** [spacetelescope/asdf#505]
Not sure if this is a bug, or a usage error that I haven't figured out how to do properly.

I try to store arrays externally, as shown in the [documentation](https://asdf.readthedocs.io/en/latest/asdf/features.html#external-references), by calling the ``set_array_storage()`` method for an array.
Writing to file(s) works nicely as intended, but when reading from disk, a ``ValueError`` is raised, that complains about a relative URL. Manually editing the YAML element to contain the absolute path of the external binary solves the read issue, but that is probably not the intended way to do things.

Here is a sample:
```python
import numpy as np
import asdf

data = np.random.rand(100, 100)
tree = {'data': data}
fh = asdf.AsdfFile(tree)
fh.set_array_storage(data, 'external')
fh.write_to('test/test.asdf')
fh.close()
del data
fh = asdf.open('test/test.asdf', 'r')
d = fh.tree['data']
# error is raised on data access
print(d[:10, :10])
```

Command line output
```bash
$ python asdf-bug.py 
Traceback (most recent call last):
  File "asdf-bug.py", line 14, in <module>
    print(d[:10, :10])
  File ".../asdf-2.1.0.dev1396-py3.6.egg/asdf/tags/core/ndarray.py", line 487, in __operation__
    return getattr(self._make_array(), name)(*args)
  File ".../asdf-2.1.0.dev1396-py3.6.egg/asdf/tags/core/ndarray.py", line 246, in _make_array
    block = self.block
  File ".../asdf-2.1.0.dev1396-py3.6.egg/asdf/tags/core/ndarray.py", line 311, in block
    self._block = self._asdffile.blocks.get_block(self._source)
  File ".../asdf-2.1.0.dev1396-py3.6.egg/asdf/block.py", line 640, in get_block
    source, do_not_fill_defaults=True)
  File ".../asdf-2.1.0.dev1396-py3.6.egg/asdf/asdf.py", line 344, in open_external
    resolved_uri = self.resolve_uri(base_uri)
  File ".../asdf-2.1.0.dev1396-py3.6.egg/asdf/asdf.py", line 320, in resolve_uri
    return generic_io.resolve_uri(self.uri, uri)
  File ".../asdf-2.1.0.dev1396-py3.6.egg/asdf/generic_io.py", line 150, in resolve_uri
    "Resolved to relative URL")
ValueError: Resolved to relative URL
```

**Comment by drdavella** [comment]
Hi @isonder, thanks for the feedback!

The problem appears to be on this line:
```python
fh = asdf.open('test/test.asdf', 'r')
```

The `'r'` argument is being interpreted as the `uri` keyword argument since no keyword is given. To fix the problem, change the line to this instead:
```python
fh = asdf.open('test/test.asdf', mode='r')
```

Or you can just omit the `mode` argument entirely since it defaults to `'r'` anyway:
```python
fh = asdf.open('test/test.asdf')
```

It might be possible to have a better error message for this so that it would have been more obvious to you what the exact problem was.
