### ISSUE TITLE
Saving arrays from np.broadcast_arrays fails

### ISSUE THREAD

**Issue by Cadair** [spacetelescope/asdf#506]
This:
```python
def test_broadcasting(tmpdir):
   attrs = np.broadcast_arrays(np.array([10,20]), np.array(10), np.array(10))
   tree = {'one': attrs[0],
           'two': attrs[1],
           'three': attrs[2]}
   assert_roundtrip_tree(tree, tmpdir)
```

Fails with a 
```
E           jsonschema.exceptions.ValidationError: {'shape': [2], 'source': 1, 'datatype': 'int64', 'byteorder': 'little', 'strides': [0]} is not valid under any of the given schemas
```

(full traceback: https://gist.github.com/Cadair/9ff970a06c4f90bf409a86b4022505f8)

I am assuming it's a problem with 'strides'

**Comment by Cadair** [comment]
I seems that the schema for `ndarray` is not flexible enough with it's strides
```
>>> attrs = np.broadcast_arrays(np.array([[10,20],[30,40]]), np.array(10), np.array(10))
>>> attrs
[array([[10, 20],
       [30, 40]]), array([[10, 10],
       [10, 10]]), array([[10, 10],
       [10, 10]])]
>>> attrs[1].strides
(0, 0)
```
https://github.com/spacetelescope/asdf-standard/blob/master/schemas/stsci.edu/asdf/core/ndarray-1.0.0.yaml#L354

**Comment by Cadair** [comment]
This section of the numpy documentation seems relevant: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray

I think the easiest solution to this is to change the ndarray schema to also allow lists of length N (where N is the dimensionality of the array). I don't know if this would have knock-on effects in other language / array type implementations of asdf?

**Comment by drdavella** [comment]
I'm beginning to wonder whether `stride` should be encoded at all as part of the schema, since it seems like an implementation detail of `numpy.ndarray` that may have no bearing on other implementations. The right thing to do in this case might be simply to copy the broadcasted array to the file. Although this takes up more memory on disk, it is implementation-agnostic.
