### ISSUE TITLE
Dev version has version number lower than release

### ISSUE THREAD

**Issue by pllim** [spacetelescope/asdf#690]
I tried installing `asdf` from source using `setup.py install`. That gave me `2.3.1a1.dev110+g341ec87`. However, `pip install asdf` (the released version) gave me `2.3.3`. As a result, dev version of `jwst` (`0.13.8a0.dev131+g9a260957`) complains that dev version of `asdf` is too old!

For sanity check, here is the latest commit in the history of my clone:
```
$ git log
commit 341ec877500d736aa184419f7993c01263ffaed0 (HEAD -> master, upstream/master)
Author: Larry Bradley <...>
Date:   Thu Jul 25 11:10:39 2019 -0400

    Update install docs to include submodule initialization [docs only]
```

**Comment by pllim** [comment]
If I install using
```
pip install git+https://github.com/spacetelescope/asdf.git@master#egg=asdf
```
then I get `asdf-2.4.0.dev61+g341ec87` 🤷‍♀

**Comment by jdavies-st** [comment]
Did you do a fresh pull of the tags as well?  Version is built from the tag.
```
$ git pull upstream master --tags
```

**Comment by pllim** [comment]
That's probably it. Thanks!
