### ISSUE TITLE
semantic_version.SpecItem is deprecated

### ISSUE THREAD

**Issue by nden** [spacetelescope/asdf#702]
`semantic_version.Specitem` is deprecated in v 2.8 and will be removed in v 3.0. Astropy raises the `DeprecationWarning` as an error. To work around this `semantic_version` was limited in setup.py to <=2.6 but the code in `asdf.versioning.py` needs a replacement of the deprecated object.

**Comment by pllim** [comment]
Why not get rid of `semantic_version` and use `setuptools_scm`?

**Comment by jdavies-st** [comment]
`asdf` already uses `setuptools_scm`.  I think this versioning has to do with schema versioning in the ASDF standard.

**Comment by pllim** [comment]
You mean this?

https://github.com/spacetelescope/asdf/blob/dcccfd0652db9266e74a53abcb83c37e8381304f/asdf/versioning.py#L161-L167

Hmm... That list doesn't seem to corresponding to [asdf-standard releases](https://github.com/spacetelescope/asdf-standard/releases). Maybe a `minversion` would suffice? :woman_shrugging:

**Comment by pllim** [comment]
Also, maybe you don't need a third-party package to do version string parsing. Then you free yourselves of this issue completely, now and forever.

**Comment by nden** [comment]
As mentioned in [this comment](https://github.com/spacetelescope/asdf/pull/700#issuecomment-553606850) look into using `SimpleSpec` or `BaseSpec`.
