### ISSUE TITLE
update package version on conda-forge

### ISSUE THREAD

**Issue by CagtayFabry** [spacetelescope/asdf#713]
The currently available "official" version using conda still seems to be 2.3.1 on the conda-forge channel
Are there any plans to update the feedstock to newer versions (>=2.4.1) of asdf in the near future?

great project btw. 👍

**Comment by nden** [comment]
@CagtayFabry We are currently a bit short on resources and  the conda-forge was dropped. We'll update it in the next couple of weeks. I'll keep this open as a reminder. Thanks for the feedback!

**Comment by CagtayFabry** [comment]
Sounds great, just wasn't sure if you planned on dropping conda support or if I can keep my conda based setup as is long term.
Thanks for getting back so quickly on this

**Comment by nden** [comment]
@CagtayFabry The latest release of asdf has been uploaded to conda-forge. Sorry for the delay.

**Comment by CagtayFabry** [comment]
@nden Thanks once again !
