### ISSUE TITLE
Need a new asdf release

### ISSUE THREAD

**Issue by pllim** [spacetelescope/asdf#714]
Hello! `astropy` is doing a campaign to clean up test warnings for v4.0 (see astropy/astropy#7928 and related PRs). Unfortunately, a number of them are caused by `asdf` due to `astropy.io.misc.asdf` tests. It seems like the tests need a YAML file that is not in your released version (2.4.2) but is in dev. Can you please make a new release soon? We are grabbing `asdf` from [PyPI](https://pypi.org/project/asdf/).

cc @astrofrog

**Comment by jdavies-st** [comment]
I see the warnings here:

https://travis-ci.org/astropy/astropy/jobs/609284637#L1821

**Comment by nden** [comment]
As discussed offline the best way to handle these atthe moment is to xskip them conditionally on the version of asdf. It's generally a chicken and egg problem where new schemas go in asdf and the corresponding tags go in astropy. There's no straightforward way to resolve it.
