### ISSUE TITLE
'asdf-standard/schemas' does not exist

### ISSUE THREAD

**Issue by baerbock** [spacetelescope/asdf#719]
I'm getting `error: package directory 'asdf-standard/schemas' does not exist` when using a standard

```
python setup.py build
python setup.py install --root=${pkgdir} --prefix=/usr --optimize=1 
```

**Comment by nden** [comment]
@baerbock Are you installing from a github clone? If so you need to run
```
cd asdf
git submodule update --init
```
`asdf-standard` is a submodule and needs to be initialized before a build.

**Comment by baerbock** [comment]
Thanks!
