### ISSUE TITLE
test_get_default_resolver failure

### ISSUE THREAD

**Issue by olebole** [spacetelescope/asdf#731]
When building and testing 2.5.0, I get the following failure:

```
__________________________ test_get_default_resolver ___________________________

    def test_get_default_resolver():
        resolver = extension.get_default_resolver()
    
        result = resolver('tag:stsci.edu:asdf/core/ndarray-1.0.0')
    
>       assert result.endswith("asdf-standard/schemas/stsci.edu/asdf/core/ndarray-1.0.0.yaml")
E       AssertionError: assert False
E        +  where False = <built-in method endswith of str object at 0x7fabc77683a0>('asdf-standard/schemas/stsci.edu/asdf/core/ndarray-1.0.0.yaml')
E        +    where <built-in method endswith of str object at 0x7fabc77683a0> = 'file:///build/python-asdf-2.5.0/.pybuild/cpython3_3.8_asdf/build/asdf/schemas/stsci.edu/asdf/core/ndarray-1.0.0.yaml'.endswith

asdf/tests/test_api.py:437: AssertionError
```
This could be resolved by removing the first directory part of the string: `…endswith("/schemas/stsci.edu/asdf/core/ndarray-1.0.0.yaml")`.
The Debian packaqe is built from the Pypi package.

**Comment by eslavich** [comment]
Thanks for the report!  We hadn't been regularly testing against an installed asdf package, so I added that to our Travis jobs and adjusted the string like you suggested.  The fix was just released in version [2.5.1](https://github.com/spacetelescope/asdf/releases/tag/2.5.1).
