### ISSUE TITLE
Serialization of models with circular definitions of user inverses fails

### ISSUE THREAD

**Issue by mcara** [spacetelescope/asdf#744]
This is essentially xref to https://github.com/spacetelescope/tweakwcs/issues/97

Example of a failure:

```
from asdf import AsdfFile
from astropy.modeling.models import Mapping, Identity, Const1D
c2tan = ((Mapping((0, 1, 2)) / Mapping((0, 0, 0), n_inputs=3)) | Mapping((1, 2)))
tan2c = (Mapping((0, 0, 1), n_inputs=2) | (Const1D(1) & Identity(2)))
c2tan.inverse = tan2c
tan2c.inverse = c2tan # <- comment this out to make the model serializable
AsdfFile({'c2tan': c2tan})  # recursion limit error
```

In my opinion `tan2c.inverse = c2tan` should work.

**Comment by eslavich** [comment]
#745 is a prerequisite to fixing this

**Comment by eslavich** [comment]
We'll need some way to keep global state during a call to custom_tree_to_tagged_tree, so that we can re-use converted tree nodes during nested calls back to custom_tree_to_tagged_tree.
