### ISSUE TITLE
SubclassMetadata type refers to schema that doesn't exist

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/asdf#748]
The library defines a [SubclassMetadata](https://github.com/spacetelescope/asdf/blob/0349ebb0666b16ee40d20a157327936c0b99f273/asdf/tags/core/__init__.py#L59) type that refers to a schema that doesn't exist in the asdf-standard repo.  Should we add one?

**Comment by jdavies-st** [comment]
This is related to https://github.com/spacetelescope/gwcs/issues/128 and #563, the desire to serialize subclasses of a known type.

Agree we should add one, though I don't know what is involved.
