### ISSUE TITLE
Files written by current master fail when opened with asdf 2.5.1

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/asdf#753]
Due to #728, files written by code in master include a `package` field in extension metadata, which causes version 2.5.1 of this library to fail to deserialize ExtensionMetadata due at this line:

https://github.com/spacetelescope/asdf/blob/2.5.1/asdf/tags/core/__init__.py#L34

(the old `ExtensionMetadata.__init__` doesn't have a `package` parameter)

Should we mitigate this somehow, or accept that 2.6.0 will write files that can't be read by earlier versions?

@nden @perrygreenfield

**Comment by jdavies-st** [comment]
Maybe a 2.5.2 release fixing the line above for the 2.5 series, fix it for 2.6.0?  And in the meantime have deprecations until 3.0.0 is released?

**Comment by eslavich** [comment]
This was resolved by reverting the change to the name of the field
