### ISSUE TITLE
Create asdf-users and asdf-developers google groups

### ISSUE THREAD

**Issue by perrygreenfield** [spacetelescope/asdf#757]
Using the following text for the announcement:

Because there are users of ASDF (Advanced Scientific Data Format: https://asdf.readthedocs.io/en/latest/) outside of STScI and that we have encountered issues that would benefit from feedback from such users, we are creating two new mailing lists for ASDF. One will be user-focused (asdf-users) and one more developer-focused (asdf-developers). These will permit general discussions, but also allow us to make announcements and raise issues that the user and developer communities should be aware of.

To avoid spammers, we require requests for group membership.

https://groups.google.com/forum/#!forum/asdf-users

https://groups.google.com/forum/#!forum/asdf-developers

**Comment by NumesSanguis** [comment]
Not that familiar with Google Groups, but it would it be possible to give read-only access to people without group membership?

In the current situation, people who have a question that unbeknownst already has been answered before, first have to wait for membership acceptance, to find out that the answer already existed.

Read-only should prevent the spammer problem.

**Comment by nden** [comment]
@NumesSanguis The list should be visible now.
