### ISSUE TITLE
How to keep asdf-standard subdirectory up to date?

### ISSUE THREAD

**Issue by dhomeier** [spacetelescope/asdf#759]
Apologies for the possibly naïve newbie question, but is there a canonical procedure recommended how to update the `asdf-standard` subdirectory? I have just updated my local asdf clone to the latest master (f58dc868), with `git status` still showing that `asdf-standard` is modified; but the diff only indicates it apparently has an unexpected commit no.

Building and installing runs smoothly, but 95 % of the tests are failing catastrophically with `ValueError: Don't know how to write out ASDF version 1.4.0`
and the like; and indeed there is no
`schemas/stsci.edu/asdf/version_map-1.4.0.yaml` either in the installed asdf tree or the `asdf-standard` in the git repo. So how does the git control of the included subdirectories work - is one supposed to manually clone and update them from the right location (removing it entirely and getting a fresh checkout only creates an empty `asdf-standard` directory, and from there on everything fails)?

P.S.: browsing the related issues I found that initialising an empty `asdf-standard` is recommended via
`git submodule update --init`
which solved the last part of the problem and now provided me with up-to-date version_maps. This had been added to the README in #215, but apparently disappeared again since (cf. also #719). Also it is still not clear how to apply this to updating an existing asdf-standard submodule.

**Comment by eslavich** [comment]
Submodules are new to me, but I'll take a crack at answering this.  It looks like git's default behavior is to fetch the submodule when pulling changes to the parent repository, but not automatically update it.  This command updates the submodule manually:

```
git submodule update
```

Another option is to configure git to automatically update the submodule to match the parent repository's commit pointer.  You can do that for your clone with this command:

```
git config submodule.recurse true
```

Or globally, for every repo you've cloned:

```
git config --global submodule.recurse true
```

I'm glad you asked -- I didn't have this option set on my own system, it makes managing the submodule much less annoying :)

**Comment by eslavich** [comment]
I agree that we should revive the submodule instructions in the readme (and include this new trick), I'll open a separate issue to address that.

**Comment by dhomeier** [comment]
> Another option is to configure git to automatically update the submodule to match the parent repository's commit pointer. You can do that for your clone with this command:
> 
> ```
> git config submodule.recurse true
> ```

Thanks, that was just the kind of solution I was looking for!
