### ISSUE TITLE
Update the release procedures WIKI

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/asdf#761]
Update the release procedures WIKI in this repo to reflect the release process.

Or automate it.  =)

**Comment by eslavich** [comment]
This page has been updated:

https://github.com/spacetelescope/asdf/wiki/Release-Process

Anything missing?

**Comment by nden** [comment]
These procedure skips updating the `stable` branch and instead puts the release tag on the release branch. I guess that's fine but it means a release branch cannot be deleted and there should be a note about this if we choose to go that way. The initial motivation for having a stable branch was to have the option of providing two versions of the documentation on readthedocs - public release and dev.

**Comment by eslavich** [comment]
Oh hmm... I didn't think about that.  There is a (possibly new) readthedocs feature that will build docs for tags as they appear and automatically set them as the default documentation, so we could use that to have docs hosted for both the latest master and latest release version.

If we continue tagging the stable branch, is there an easy way (for example) to release a patch on 2.x when 3.0 is already released and tagged?

**Comment by eslavich** [comment]
Oh hmm... I didn't think about that.  There is a (possibly new) readthedocs feature that will build docs for tags as they appear and automatically set them as the default documentation, so we could use that to have docs hosted for both the latest master and latest release version.

If we continue tagging the stable branch, is there an easy way (for example) to release a patch on 2.x when 3.0 is already released and tagged?

**Comment by jdavies-st** [comment]
I think as long as you do a merge commit from the release branch to `stable`, and the tag is still there (i.e. it's the same commit), I think Ed's way is fine.  But he should verify that it works.  It really depends on the history of `stable`.  If anything was ever cherry-picked onto stable, then that won't work I think.

I guess the nice thing about tagging on the release branch and merging to `stable` is that it will always work.  One set of instructions.  As long as we are consistent, that's good.

As for maintaining 2.x after 3.0 is released, those tags would also continue to go on the release branches, they just would not get merged to to `stable`.

**Comment by eslavich** [comment]
I added some additional sections on maintaining the stable branch and running astropy/jwst/etc test suites.

**Comment by jdavies-st** [comment]
It looks like the `astropy` folks blow away and rewrite their stable branch for every new release (see step 4 below).

https://docs.astropy.org/en/stable/development/releasing.html#post-release-procedures

**Comment by eslavich** [comment]
... and another section on tagging master for further development
