### ISSUE TITLE
simpler example for creating arrays in README.rst

### ISSUE THREAD

**Issue by perrygreenfield** [spacetelescope/asdf#762]
Peter Teuben points out that the example on readthedocs (which comes from the README.rst) of the following:

```
sequence = np.array([x for x in range(100)])
squares = np.array([x**2 for x in range(100)])
```

is better expressed as 

```
sequence = np.arange(100)
squares  = sequence**2
```

It is hard to argue with that.

**Comment by nden** [comment]
Fixed in #763
