### ISSUE TITLE
Stop using deprecated pytest initializer

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/asdf#789]
This warning started appearing with pytest 5.4:

```
pytest.PytestDeprecationWarning: direct construction of AsdfSchemaFile has been deprecated, please use AsdfSchemaFile.from_parent
```

https://docs.pytest.org/en/latest/deprecations.html#node-construction-changed-to-node-from-parent has advice on how to continue to support multiple pytest versions.

**Comment by pllim** [comment]
cc @bsipocz

**Comment by bsipocz** [comment]
yes, this is the one I see. If it comes up in CI, we should just add it to the ignore warnings list, I don't think this alone should trigger a version bump.
