### ISSUE TITLE
Referencing an array in the same ASDF file

### ISSUE THREAD

**Issue by JorisDeRidder** [spacetelescope/asdf#800]
I would like to save many ultra-high-resolution spectra to the same ASDF file. The total size of  all these spectra combined does not fit into my computer's memory, so I have to use a loop to incrementally update the tree: 

1. asdf.open("myfile.asdf", mode="rw")
2. add the wavelength and the flux arrays to the tree
3. update()
4. close()

However, many (but not all) of the wavelength arrays are exactly the same, so in these cases I would prefer that it's stored only once, and refer to that array where possible. I only see one way to create references and that is with make_reference(). However, the docs mention that the function is designed to assign a reference to *another* tree. Should I also be using make_reference() to make a reference in the *same* tree, or is there a better way?

**Comment by perrygreenfield** [comment]
The last release makes this easy so long as the underlying array is exactly the same object (i.e., not copies of the same array). But if you look at PR #777 you will see that one of the new features is the automatic recognition of identical objects and the use of YAML references to indicate that in the YAML. This is part of ASDF v2.6 (is that what you are using?). Your case could be more complicated in that you are adding these over time through the update method and we'll have to check if references are handled properly in that case. Could you check that you are using exactly the same array object?

**Comment by JorisDeRidder** [comment]
I updated to v2.6, and it seems to work as expected. Thanks for the info, it's a nice feature!
